version: 0.2

env:
  variables:
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started
      - ng build
  docker-build:
    commands:
      - echo Building Docker image
      - docker build -t my-image .
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: "dist*"
